sudo: false

language: python
cache: pip
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6


before_install:
  - pip install -r requirements-test.txt

install:
  - pip install -r requirements.txt

script:
  - pytest --verbose
  - pylint narwhal tests examples
  - flake8 --verbose
